src/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include("core.urls")),
    path('minegocio/', include("minegocio.urls")),
    path('', include("core.urls")),
    

]

src/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
]

src/minegocio/urls.py
from django.urls import path
from .views import (index, about, vendedor_create, vendedor_list, 
                    transaccion_create, transaccion_list, 
                    reporte_create, reporte_list, vendedor_detail,
                    vendedor_edit, vendedor_delete,transaccion_detail, 
                    transaccion_edit, transaccion_delete,
                    login_view, signup_view, view_profile, edit_profile)
from django.contrib.auth.views import LogoutView

app_name = "minegocio"

urlpatterns = [
    path('', index, name="index"),
    path('about/', about, name="about"),
    path("vendedor/list/", vendedor_list, name="vendedor_list"),
    path("vendedor/create/", vendedor_create, name="vendedor_create"),
    path("vendedor/detail/<int:vendedor_id>/", vendedor_detail, name="vendedor_detail"),
    path("vendedor/edit/<int:vendedor_id>/", vendedor_edit, name="vendedor_edit"),
    path("vendedor/delete/<int:vendedor_id>/", vendedor_delete, name="vendedor_delete"),
    path("transaccion/list/", transaccion_list, name="transaccion_list"),
    path("transaccion/create/", transaccion_create, name="transaccion_create"),
    path("transaccion/detail/<int:transaccion_id>/", transaccion_detail, name="transaccion_detail"),
    path("transaccion/edit/<int:transaccion_id>/", transaccion_edit, name="transaccion_edit"),
    path("transaccion/delete/<int:transaccion_id>/", transaccion_delete, name="transaccion_delete"),
    path("reporte/list/", reporte_list, name="reporte_list"),
    path("reporte/create/", reporte_create, name="reporte_create"),
    path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', view_profile, name='view_profile'),
    path('profile/edit/', edit_profile, name='edit_profile'),
]

src/core/models.py
from django.db import models

# Create your models here.

src/core/views.py
from django.shortcuts import render

# Create your views here.

def index(request): 
    return render(request, 'core/index.html',)
def about(request): 
    return render(request, 'core/about.html',)

src/core/templates/core/componentes/ContactForm.html
<!-- Contact-->
<section class="page-section" id="contact">
    <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-lg-8 col-xl-6 text-center">
            <h2 class="mt-0">Let's Get In Touch!</h2>
            <hr class="divider" />
            <p class="text-muted mb-5">Ready to start your next project with us? Send us a messages and we will get back to you as soon as possible!</p>
        </div>
    </div>

<div class="row gx-4 gx-lg-5 justify-content-center mb-5">
    <div class="col-lg-6">
        <!-- * * * * * * * * * * * * * * *-->
        <!-- * * SB Forms Contact Form * *-->
        <!-- * * * * * * * * * * * * * * *-->
        <!-- This form is pre-integrated with SB Forms.-->
        <!-- To make this form functional, sign up at-->
        <!-- https://startbootstrap.com/solution/contact-forms-->
        <!-- to get an API token!-->
        <form id="contactForm" data-sb-form-api-token="API_TOKEN">
            <!-- Name input-->
            <div class="form-floating mb-3">
                <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                <label for="name">Full name</label>
                <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
            </div>
            <!-- Email address input-->
            <div class="form-floating mb-3">
                <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                <label for="email">Email address</label>
                <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
            </div>
            <!-- Phone number input-->
            <div class="form-floating mb-3">
                <input class="form-control" id="phone" type="tel" placeholder="(123) 456-7890" data-sb-validations="required" />
                <label for="phone">Phone number</label>
                <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
            </div>
            <!-- Message input-->
            <div class="form-floating mb-3">
                <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                <label for="message">Message</label>
                <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
            </div>
            <!-- Submit success message-->
            <!---->
            <!-- This is what your users will see when the form-->
            <!-- has successfully submitted-->
            <div class="d-none" id="submitSuccessMessage">
                <div class="text-center mb-3">
                    <div class="fw-bolder">Form submission successful!</div>
                    To activate this form, sign up at
                    <br />
                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                </div>
            </div>
            <!-- Submit error message-->
            <!---->
            <!-- This is what your users will see when there is-->
            <!-- an error submitting the form-->
            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
            <!-- Submit Button-->
            <div class="d-grid"><button class="btn btn-primary btn-xl disabled" id="submitButton" type="submit">Submit</button></div>
        </form>
    </div>
</div>

<div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-lg-4 text-center mb-5 mb-lg-0">
        <i class="bi-phone fs-2 mb-3 text-muted"></i>
        <div>+1 (555) 123-4567</div>
    </div>
</div>
</div>
</section>

src/core/templates/core/componentes/card.html
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="assets/img/portfolio/fullsize/1.jpg" title="Project Name">
        <img class="img-fluid" src="assets/img/portfolio/thumbnails/1.jpg" alt="..." />
        <div class="portfolio-box-caption">
            <div class="project-category text-white-50">Category</div>
            <div class="project-name">Project Name</div>
        </div>
    </a>
</div>
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="assets/img/portfolio/fullsize/2.jpg" title="Project Name">
        <img class="img-fluid" src="assets/img/portfolio/thumbnails/2.jpg" alt="..." />
        <div class="portfolio-box-caption">
            <div class="project-category text-white-50">Category</div>
            <div class="project-name">Project Name</div>
        </div>
    </a>
</div>
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="assets/img/portfolio/fullsize/3.jpg" title="Project Name">
        <img class="img-fluid" src="assets/img/portfolio/thumbnails/3.jpg" alt="..." />
        <div class="portfolio-box-caption">
            <div class="project-category text-white-50">Category</div>
            <div class="project-name">Project Name</div>
        </div>
    </a>
</div>
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="assets/img/portfolio/fullsize/4.jpg" title="Project Name">
        <img class="img-fluid" src="assets/img/portfolio/thumbnails/4.jpg" alt="..." />
        <div class="portfolio-box-caption">
            <div class="project-category text-white-50">Category</div>
            <div class="project-name">Project Name</div>
        </div>
    </a>
</div>
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="assets/img/portfolio/fullsize/5.jpg" title="Project Name">
        <img class="img-fluid" src="assets/img/portfolio/thumbnails/5.jpg" alt="..." />
        <div class="portfolio-box-caption">
            <div class="project-category text-white-50">Category</div>
            <div class="project-name">Project Name</div>
        </div>
    </a>
</div>
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="assets/img/portfolio/fullsize/6.jpg" title="Project Name">
        <img class="img-fluid" src="assets/img/portfolio/thumbnails/6.jpg" alt="..." />
        <div class="portfolio-box-caption p-3">
            <div class="project-category text-white-50">Category</div>
            <div class="project-name">Project Name</div>
        </div>
    </a>
</div>

src/core/templates/core/componentes/download.html
<!-- Call to action-->
<section class="page-section bg-dark text-white">
    <div class="container px-4 px-lg-5 text-center">
    <h2 class="mb-4">Free Download at Start Bootstrap!</h2>
    <a class="btn btn-light btn-xl" href="https://startbootstrap.com/theme/creative/">Download Now!</a>
    </div>
    </section>

src/core/templates/core/componentes/footer.html
 <!-- Footer-->
 <footer class="bg-light py-2 fixed-bottom">
    <div class="container px-2 px-lg-5">
        <div class="small text-center text-muted">Copyright &copy; 2023 - Company Name</div></div>
</footer>

src/core/templates/core/componentes/navbar.html
 <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#page-top">Mi negocio</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto my-2 my-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:about' %}">Conocenos</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'minegocio:index' %}">Mi negocio</a></li>
                    <li class="nav-item">
                        <form method="POST" action="{% url 'minegocio:logout' %}" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link nav-link" style="padding: 0; border: none; background: none;">Cerrar sesión</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:about' %}">Conocenos</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'minegocio:login' %}">Iniciar sesión</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

src/core/templates/core/componentes/services.html
<!-- Services-->
    <section class="page-section" id="services">
    <div class="container px-4 px-lg-5">
    <h2 class="text-center mt-0">At Your Service</h2>
    <hr class="divider" />
    <div class="row gx-4 gx-lg-5">
        <div class="col-lg-3 col-md-6 text-center">
            <div class="mt-5">
                <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                <h3 class="h4 mb-2">Sturdy Themes</h3>
                <p class="text-muted mb-0">Our themes are updated regularly to keep them bug free!</p>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
            <div class="mt-5">
                <div class="mb-2"><i class="bi-laptop fs-1 text-primary"></i></div>
                <h3 class="h4 mb-2">Up to Date</h3>
                <p class="text-muted mb-0">All dependencies are kept current to keep things fresh.</p>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
            <div class="mt-5">
                <div class="mb-2"><i class="bi-globe fs-1 text-primary"></i></div>
                <h3 class="h4 mb-2">Ready to Publish</h3>
                <p class="text-muted mb-0">You can use this design as is, or you can make changes!</p>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
            <div class="mt-5">
                <div class="mb-2"><i class="bi-heart fs-1 text-primary"></i></div>
                <h3 class="h4 mb-2">Made with Love</h3>
                <p class="text-muted mb-0">Is it really open source if it's not made with love?</p>
            </div>
        </div>
    </div>
    </div>
    </section>